
export const ADMIN_LOGIN_START = 'ADMIN_LOGIN_START'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR'

export const ADMIN_CHANGE_PASSWORD_START = 'ADMIN_CHANGE_PASSWORD_START'
export const ADMIN_CHANGE_PASSWORD_SUCCESS = 'ADMIN_CHANGE_PASSWORD_SUCCESS'
export const ADMIN_CHANGE_PASSWORD_ERROR = 'ADMIN_CHANGE_PASSWORD_ERROR'

export const ADMIN_LOGOUT_START = 'ADMIN_LOGOUT_START'
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS'
export const ADMIN_LOGOUT_ERROR = 'ADMIN_LOGOUT_ERROR'

export const LOAD_USERS_START = "LOAD_USERS_START"
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR"

export const ADD_NEW_EMPLOYEE_START = 'ADD_NEW_EMPLOYEE_START'
export const ADD_NEW_EMPLOYEE_SUCCESS = 'ADD_NEW_EMPLOYEE_SUCCESS'
export const ADD_NEW_EMPLOYEE_ERROR = 'ADD_NEW_EMPLOYEE_ERROR'

export const UPDATE_EMPLOYEE_START = 'UPDATE_EMPLOYEE_START'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR'

export const DELETE_EMPLOYEE_START = 'DELETE_EMPLOYEE_START'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR'

export const GET_SINGLE_EMPLOYEE_START = 'GET_SINGLE_EMPLOYEE_START'
export const GET_SINGLE_EMPLOYEE_SUCCESS = 'GET_SINGLE_EMPLOYEE_SUCCESS'
export const GET_SINGLE_EMPLOYEE_ERROR = 'GET_SINGLE_EMPLOYEE_ERROR'

export const GET_SINGLE_EMPLOYEE_ASSIGNMENT_START = 'GET_SINGLE_EMPLOYEE_ASSIGNMENT_START'
export const GET_SINGLE_EMPLOYEE_ASSIGNMENT_SUCCESS = 'GET_SINGLE_EMPLOYEE_ASSIGNMENT_SUCCESS'
export const GET_SINGLE_EMPLOYEE_ASSIGNMENT_ERROR = 'GET_SINGLE_EMPLOYEE_ASSIGNMENT_ERROR'


