export const LOAD_ALLOCATIONS_START = "LOAD_ALLOCATIONS_START"
export const LOAD_ALLOCATIONS_SUCCESS = "LOAD_ALLOCATIONS_SUCCESS"
export const LOAD_ALLOCATIONS_ERROR = "LOAD_ALLOCATIONS_ERROR"

export const NEW_ALLOCATION_START = 'NEW_ALLOCATION_START'
export const NEW_ALLOCATION_SUCCESS = 'NEW_ALLOCATION_SUCCESS'
export const NEW_ALLOCATION_ERROR = 'NEW_ALLOCATION_ERROR'

export const UPDATE_ALLOCATION_START = 'UPDATE_ALLOCATION_START'
export const UPDATE_ALLOCATION_SUCCESS = 'UPDATE_ALLOCATION_SUCCESS'
export const UPDATE_ALLOCATION_ERROR = 'UPDATE_ALLOCATION_ERROR'

export const DELETE_ALLOCATION_START = 'DELETE_ALLOCATION_START'
export const DELETE_ALLOCATION_SUCCESS = 'DELETE_ALLOCATION_SUCCESS'
export const DELETE_ALLOCATION_ERROR = 'DELETE_ALLOCATION_ERROR'
