export const NEW_ASSIGN_START = 'NEW_ASSIGN_START'
export const NEW_ASSIGN_SUCCESS = 'NEW_ASSIGN_SUCCESS'
export const NEW_ASSIGN_ERROR = 'NEW_ASSIGN_ERROR'

export const UPDATE_ASSIGN_START = 'UPDATE_ASSIGN_START'
export const UPDATE_ASSIGN_SUCCESS = 'UPDATE_ASSIGN_SUCCESS'
export const UPDATE_ASSIGN_ERROR = 'UPDATE_ASSIGN_ERROR'