export const LOAD_COMBO_START = "LOAD_COMBO_START"
export const LOAD_COMBO_SUCCESS = "LOAD_COMBO_SUCCESS"
export const LOAD_COMBO_ERROR = "LOAD_COMBO_ERROR"

export const GET_SINGLE_COMBO_START = 'GET_SINGLE_COMBO_START'
export const GET_SINGLE_COMBO_SUCCESS = 'GET_SINGLE_COMBO_SUCCESS'
export const GET_SINGLE_COMBO_ERROR = 'GET_SINGLE_COMBO_ERROR'

export const GET_ITEMS_BY_CATEGORY_START = 'GET_ITEMS_BY_CATEGORY_START'
export const GET_ITEMS_BY_CATEGORY_SUCCESS = 'GET_ITEMS_BY_CATEGORY_SUCCESS'
export const GET_ITEMS_BY_CATEGORY_ERROR = 'GET_ITEMS_BY_CATEGORY_ERROR'
