export const LOAD_COMBO_START = "LOAD_COMBO_START"
export const LOAD_COMBO_SUCCESS = "LOAD_COMBO_SUCCESS"
export const LOAD_COMBO_ERROR = "LOAD_COMBO_ERROR"

export const CREATE_COMBO_START = 'CREATE_COMBO_START'
export const CREATE_COMBO_SUCCESS = 'CREATE_COMBO_SUCCESS'
export const CREATE_COMBO_ERROR = 'CREATE_COMBO_ERROR'

export const UPDATE_COMBO_START = 'UPDATE_COMBO_START'
export const UPDATE_COMBO_SUCCESS = 'UPDATE_COMBO_SUCCESS'
export const UPDATE_COMBO_ERROR = 'UPDATE_COMBO_ERROR'

export const DELETE_COMBO_START = 'DELETE_COMBO_START'
export const DELETE_COMBO_SUCCESS = 'DELETE_COMBO_SUCCESS'
export const DELETE_COMBO_ERROR = 'DELETE_COMBO_ERROR'

export const GET_COMBO_BYID_START = 'GET_COMBO_BYID_START'
export const GET_COMBO_BYID_SUCCESS = 'GET_COMBO_BYID_SUCCESS'
export const GET_COMBO_BYID_ERROR = 'GET_COMBO_BYID_ERROR'