
export const LOAD_DEPARTMENT_START = "LOAD_DEPARTMENT_START"
export const LOAD_DEPARTMENT_SUCCESS = "LOAD_DEPARTMENT_SUCCESS"
export const LOAD_DEPARTMENT_ERROR = "LOAD_DEPARTMENT_ERROR"

export const ADD_NEW_DEPARTMENT_START = 'ADD_NEW_DEPARTMENT_START'
export const ADD_NEW_DEPARTMENT_SUCCESS = 'ADD_NEW_DEPARTMENT_SUCCESS'
export const ADD_NEW_DEPARTMENT_ERROR = 'ADD_NEW_DEPARTMENT_ERROR'

export const UPDATE_DEPARTMENT_START = 'UPDATE_DEPARTMENT_START'
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS'
export const UPDATE_DEPARTMENT_ERROR = 'UPDATE_DEPARTMENT_ERROR'

export const GET_SINGLE_DEPARTMENT_START = 'GET_SINGLE_DEPARTMENT_START'
export const GET_SINGLE_DEPARTMENT_SUCCESS = 'GET_SINGLE_DEPARTMENT_SUCCESS'
export const GET_SINGLE_DEPARTMENT_ERROR = 'GET_SINGLE_DEPARTMENT_ERROR'
 
export const DELETE_DEPARTMENT_START = 'DELETE_DEPARTMENT_START'
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS'
export const DELETE_DEPARTMENT_ERROR = 'DELETE_DEPARTMENT_ERROR'