
export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START"
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const LOAD_PRODUCTS_ERROR = "LOAD_PRODUCTS_ERROR"

export const ADD_NEW_PRODUCT_START = 'ADD_NEW_PRODUCT_START'
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS'
export const ADD_NEW_PRODUCT_ERROR = 'ADD_NEW_PRODUCT_ERROR'

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'

export const GET_SINGLE_PRODUCT_START = 'GET_SINGLE_PRODUCT_START'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'
 
export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'
